In [1]:
import pandas as pd
df = pd.read_csv(r'/Users/suhaas/Machine-Learning/manu-sus-engine/Merged_dataset.csv')
df.head()

,Batch_ID,Duration_Minutes,Data_Points,Avg_Temperature,Max_Temperature,Avg_Pressure,Max_Compression_Force,Avg_Power_Consumption,Max_Motor_Speed,Avg_Humidity_Percent,...,Compression_Force,Machine_Speed,Lubricant_Conc,Moisture_Content,Tablet_Weight,Hardness,Friability,Disintegration_Time,Dissolution_Rate,Content_Uniformity
0,T001,210,211,35.222405,64.464826,0.989573,14.219469,21.821216,875.033250,38.260003,...,12.5,150,1.0,2.1,199.8,95,0.65,8.2,89.3,98.7
1,T002,242,243,34.118974,68.199612,0.990320,18.252780,21.761982,870.711447,37.468800,...,15.0,120,0.8,2.8,201.3,110,0.45,12.1,87.9,101.2
2,T003,257,258,35.232192,65.789715,0.973079,12.139067,23.328404,876.255527,36.915295,...,10.8,180,1.2,1.9,198.5,85,0.78,6.8,91.5,97.3
3,T004,231,232,37.009830,68.036694,0.969539,10.457428,21.305877,854.039596,37.631641,...,8.5,200,1.5,1.5,203.2,72,0.95,5.5,93.8,95.9
4,T005,246,247,33.918228,74.712142,0.969525,18.036629,24.982074,906.424204,36.420933,...,16.2,100,0.6,3.2,202.7,125,0.38,14.8,85.1,103.5

In [3]:
df["Energy_Consumption_kWh"] = df["Avg_Power_Consumption"] * (df["Duration_Minutes"] / 60)
df.head()

,Batch_ID,Duration_Minutes,Data_Points,Avg_Temperature,Max_Temperature,Avg_Pressure,Max_Compression_Force,Avg_Power_Consumption,Max_Motor_Speed,Avg_Humidity_Percent,...,Machine_Speed,Lubricant_Conc,Moisture_Content,Tablet_Weight,Hardness,Friability,Disintegration_Time,Dissolution_Rate,Content_Uniformity,Energy_Consumption_kWh
0,T001,210,211,35.222405,64.464826,0.989573,14.219469,21.821216,875.033250,38.260003,...,150,1.0,2.1,199.8,95,0.65,8.2,89.3,98.7,76.374255
1,T002,242,243,34.118974,68.199612,0.990320,18.252780,21.761982,870.711447,37.468800,...,120,0.8,2.8,201.3,110,0.45,12.1,87.9,101.2,87.773329
2,T003,257,258,35.232192,65.789715,0.973079,12.139067,23.328404,876.255527,36.915295,...,180,1.2,1.9,198.5,85,0.78,6.8,91.5,97.3,99.923333
3,T004,231,232,37.009830,68.036694,0.969539,10.457428,21.305877,854.039596,37.631641,...,200,1.5,1.5,203.2,72,0.95,5.5,93.8,95.9,82.027627
4,T005,246,247,33.918228,74.712142,0.969525,18.036629,24.982074,906.424204,36.420933,...,100,0.6,3.2,202.7,125,0.38,14.8,85.1,103.5,102.426504

In [4]:
#0.82 kg CO2 per kWh  (India average)
df["Carbon_Emissions_kgCO2"] = df["Energy_Consumption_kWh"] * 0.82
df.head()

,Batch_ID,Duration_Minutes,Data_Points,Avg_Temperature,Max_Temperature,Avg_Pressure,Max_Compression_Force,Avg_Power_Consumption,Max_Motor_Speed,Avg_Humidity_Percent,...,Lubricant_Conc,Moisture_Content,Tablet_Weight,Hardness,Friability,Disintegration_Time,Dissolution_Rate,Content_Uniformity,Energy_Consumption_kWh,Carbon_Emissions_kgCO2
0,T001,210,211,35.222405,64.464826,0.989573,14.219469,21.821216,875.033250,38.260003,...,1.0,2.1,199.8,95,0.65,8.2,89.3,98.7,76.374255,62.626889
1,T002,242,243,34.118974,68.199612,0.990320,18.252780,21.761982,870.711447,37.468800,...,0.8,2.8,201.3,110,0.45,12.1,87.9,101.2,87.773329,71.974129
2,T003,257,258,35.232192,65.789715,0.973079,12.139067,23.328404,876.255527,36.915295,...,1.2,1.9,198.5,85,0.78,6.8,91.5,97.3,99.923333,81.937133
3,T004,231,232,37.009830,68.036694,0.969539,10.457428,21.305877,854.039596,37.631641,...,1.5,1.5,203.2,72,0.95,5.5,93.8,95.9,82.027627,67.262654
4,T005,246,247,33.918228,74.712142,0.969525,18.036629,24.982074,906.424204,36.420933,...,0.6,3.2,202.7,125,0.38,14.8,85.1,103.5,102.426504,83.989733